/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomePanel.java
 *
 * Created on 7/06/2009, 12:15:12 AM
 */

package gui;

/**
 *
 * @author Sergio
 */
public class WelcomePanel extends javax.swing.JPanel {

    /** Creates new form WelcomePanel */
    public WelcomePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeTip1 = new javax.swing.JLabel();
        welcomeTip2 = new javax.swing.JLabel();
        welcomeTip3 = new javax.swing.JLabel();
        welcomeTip4 = new javax.swing.JLabel();

        welcomeTip1.setText("Bienvenido al programa de instalación de , este programa le guiará durante el proceso de instalación.");

        welcomeTip2.setText("Haga clic en siguiente para comenzar.");

        welcomeTip3.setText("Una vez empezado el asistente puede hacer clic en el botón Atrás en cualquier momento para corregir información");

        welcomeTip4.setText("Puede hacer clic en el botón Cancelar en cualquier momento para cancelar el proceso de instalación.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeTip1)
                    .addComponent(welcomeTip2)
                    .addComponent(welcomeTip3)
                    .addComponent(welcomeTip4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeTip1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeTip2)
                .addGap(34, 34, 34)
                .addComponent(welcomeTip3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeTip4)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel welcomeTip1;
    private javax.swing.JLabel welcomeTip2;
    private javax.swing.JLabel welcomeTip3;
    private javax.swing.JLabel welcomeTip4;
    // End of variables declaration//GEN-END:variables

}
