/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FinishedPanel.java
 *
 * Created on 7/06/2009, 12:26:03 AM
 */

package gui;

/**
 *
 * @author Sergio
 */
public class FinishedPanel extends javax.swing.JPanel {

    /** Creates new form FinishedPanel */
    public FinishedPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finisshedTip = new javax.swing.JLabel();

        finisshedTip.setText("El programa se ha instalado con éxito. Haga clic en Finalizar para terminar el asistente.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finisshedTip)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finisshedTip)
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finisshedTip;
    // End of variables declaration//GEN-END:variables

}
