/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShortcutPanel.java
 *
 * Created on 7/06/2009, 12:32:07 AM
 */

package gui;

/**
 *
 * @author Sergio
 */
public class ShortcutPanel extends javax.swing.JPanel {

    /** Creates new form ShortcutPanel */
    public ShortcutPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shortcutTip = new javax.swing.JLabel();
        shortcut = new javax.swing.JCheckBox();

        shortcutTip.setText("¿Desea crear un acceso directo en el escritorio?");

        shortcut.setText("Crear acceso directo en el escritorio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(shortcut))
                    .addComponent(shortcutTip))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shortcutTip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shortcut)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox shortcut;
    private javax.swing.JLabel shortcutTip;
    // End of variables declaration//GEN-END:variables

}
